### ISSUE TITLE
fix: Dart 2.15 generators are offline (HTTP 503)

### ISSUE THREAD

**Issue by blima-medicallyhome** [iruoy-nl/architect#23]
**Description**

The code generators at https://dart-generator.iruoy.nl are unavailable. We have several production projects that depend on these generators and need them to move forward.  

**Steps To Reproduce**

1. Go to https://app.apibuilder.io/bml/validation/0.0.1/dart_2_15_json
4. See error 503 Service Unavailable

**Expected Behavior**
Code generation functions through apibuilder.io normally.

**Comment by YouriLieverdink** [comment]
Thanks for opening an issue!

I'm currently working on the problem. I've migrated everything to a new environment which I'm still working on. I hope to finish the `dart_2_15_json` generator this week. I'm sorry for the inconvenience!

**Comment by benwaffle** [comment]
@YouriLieverdink you should join us in the Slack - https://slack.apibuilder.io/

**Comment by YouriLieverdink** [comment]
Okay! @benwaffle
