### ISSUE TITLE
dart_2_17_client generator issues

### ISSUE THREAD

**Issue by dgaxho** [iruoy-nl/architect#41]
**Description**

Seeing two issues with the dart_2_17_client generator:

1. Issue with imports from the _client.dart generated file for types in the _json.dart file - in particular for us this is manifesting whenever the _client.dart file references EnumMaps from the _json.dart file. For example:

```
final query = {
      'enumExample': EnumExampleEnumMap[enumExample]?.toString()
    };
```

results in "Undefined name 'EnumExampleEnumMap'. Try correcting the name to one that is defined, or defining the name." This can be fixed by changing the type to `_i3.EnumExampleEnumMap`.

Note that this issue is also present in the dart_2_15_client generator.

2. Runtime issue with parsing json for enum fields. In our case this json parsing code is being generated for an object with an enum field, but the code has a local var name shadowing issue:

```
(json['enumExample'] as _i2.List)
          .map((v) => EnumExampleEnumMap.entries
              .firstWhere((v) => v.value == (v as _i2.String))
              .key)
          .toList(),
```

this should be corrected to something like:

```
(json['enumExample'] as _i2.List)
          .map((v) => EnumExampleEnumMap.entries
              .firstWhere((v2) => v2.value == (v as _i2.String))
              .key)
          .toList(),
```

**Comment by YouriLieverdink** [comment]
Thank you for opening an issue!

I've addressed both problems in pull-request #42 which will soon be merged. The update should be live in 30 minutes @dgaxho!
