### ISSUE TITLE
dart_2_17_client generator issue with sealed union type mapping

### ISSUE THREAD

**Issue by dgaxho** [iruoy-nl/architect#43]
**Description**

Thanks for the recent fixes with the dart_2_17_client generator. It seems like there's still one additional issue with the support for apibuilder unions via the sealed_union dart package. When generating the json parsing support for union fields this code is generated:

```
  factory UnionExample.fromJson(_i2.dynamic json) {
    final type = (json as _i2.Map).keys.first;

    switch (type) {
      case 'unionType1':
        return UnionExample._(
            factory.first(UnionType1.fromJson(json['unionType1'])));

      case 'unionType2':
        return UnionExample._(
            factory.second(UnionType2.fromJson(json['unionType2'])));

      default:
        throw _i2.Exception();
    }
  }
``` 

This results in this compilation error: 

"The argument type 'Union2<UnionType1, UnionType2>' can't be assigned to the parameter type 'Union2Impl<UnionType1, UnionType2>'."

**Comment by YouriLieverdink** [comment]
Thanks for opening an issue!

I've resolved the issue, a new version of the generator will be available shortly. @dgaxho
