### ISSUE TITLE
fix: identical method names of different operations

### ISSUE THREAD

**Issue by YouriLieverdink** [iruoy-nl/architect#49]
**Description**

The dart 2.15 and 2.17 client generators produce resources with identical method names

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

```dart
 /// Accepts an invitation.
  _i2.Future<void> postById({required _i2.String id}) async {
    final uri = _i2.Uri.parse(baseUrl).replace(path: '/invitations/$id/accept');

    final response = await client.post(uri);

    switch (response.statusCode) {
      case 204:
        break;

      case 403:
        throw _i2.Exception();

      default:
        throw _i2.Exception();
    }
  }

  /// Declines an invitation.
  _i2.Future<void> postById({required _i2.String id}) async {
    final uri =
        _i2.Uri.parse(baseUrl).replace(path: '/invitations/$id/decline');

    final response = await client.post(uri);

    switch (response.statusCode) {
      case 204:
        break;

      case 403:
        throw _i2.Exception();

      default:
        throw _i2.Exception();
    }
  }
```

**Additional Context**

**Comment by dgaxho** [comment]
@YouriLieverdink Any updates on this? Note that this also applies for nested resources. Like for example, the same issue happens if we have GET `/invitations/$invitationId/notes/$noteId` and GET `/invitations/$invitationId/media/$mediaId`. Both of these generate duplicately named `getByInvitationId` methods. It seems like at least we should be looking at the response type and adding that as part of the method name prefix to work around this, or for the POST example that you gave (where both responses are void), maybe looking at the last part of the path?

**Comment by YouriLieverdink** [comment]
@dgaxho, Yes I've been working on it just now.

The path `/invitations/:invitationId/notes/:noteId` would now generate the following name, it that something you can work with?

```dart
getNotesByInvitationIdAndNoteId

// This can then be called via the client and the resource like
void main() {
    final client = Client(...);
    
    client.invitations.getNotesByInvitationIdAndNoteId(...);
}
```

**Comment by dgaxho** [comment]
So, I think that would definitely solve the duplicate method name issue, just want to make sure that the part after `get` in the method name is based on the response type of that api. 

I think technically it's possible for nested resources below a top level resource path to be of different types. So for example if you had:

`/invitations/$invitationId/notes/$noteId`

where the response type of that path was a `Note` model, and:

`/invitations/$invitationId/media/$mediaId`

where that response type would be a `Media` model, then I would expect methods like:

`getNoteByInvitationIdAndNoteId(...)`

and

`getMediaByInvitationIdAndNoteId(...)`

and perhaps it would make sense to pluralize those in the case of a list response.

**Comment by YouriLieverdink** [comment]
The method I've created currently only looks at the path of the operation. Looking at the return type is too much of a hassle to implement for now, maybe I'll do something like that in the future. I believe this should work for now.
