### ISSUE TITLE
fix: Don't hide status codes for error responses in _client.dart generated code

### ISSUE THREAD

**Issue by dgaxho** [iruoy-nl/architect#54]
**Description**

Sorry if arguably this is not a bug, but, for api resources that have responses like the following:

```
"responses": {
            ...
            "401": {
              "description": "Unauthorized.",
              "type": "unit"
            },
            "403": {
              "description": "Forbidden.",
              "type": "unit"
            },
            "404": {
              "description": "Not Found.",
              "type": "unit"
            }
}
```

the `_client.dart` generated code has status code handling that looks like this:

```
 // generated method start ...
    switch (response.statusCode) {
      case 200:
        // handling of success status...
      case 401:
        throw _i2.Exception();

      case 403:
        throw _i2.Exception();

      case 404:
        throw _i2.Exception();

      default:
        throw _i2.Exception();
    }
  }
 // generated method end ...
```

Unfortunately with this set up, callers of this method then lose the ability to distinguish between these different error responses. Would it make sense to define a default ApiErrorException type that at least includes the status code with the exception? For us I think this would be required to use this generated code.

**Expected Behavior**

I would expect the generated code to throw something like an ApiErrorException that includes the status code from the response, in the 401 / 403 / 404 status code cases above, so that the status code can still be looked up and other code can action on that.

**Comment by YouriLieverdink** [comment]
@dgaxho, what do you think of the solution I presented?

**Comment by dgaxho** [comment]
I think that should work. Thank you!

**Comment by dgaxho** [comment]
@YouriLieverdink Has this been released yet? Not sure if merges to dev automatically get deployed. So far not seeing the new behavior with the dart_2_17_client.

**Comment by YouriLieverdink** [comment]
@dgaxho, it gets deployed automatically every 30 minutes
